# Test Profile Configuration
# Uses PostgreSQL for integration testing

spring:
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://${TEST_DB_HOST:localhost}:${TEST_DB_PORT:5432}/${TEST_DB_NAME:knowledge_tracker_test}
    driver-class-name: org.postgresql.Driver
    username: ${TEST_DB_USERNAME:postgres}
    password: ${TEST_DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: ${TEST_DB_POOL_SIZE:5}
      minimum-idle: ${TEST_DB_MIN_IDLE:2}
      connection-timeout: ${TEST_DB_CONNECTION_TIMEOUT:30000}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Use schema.sql.bak for tests
    show-sql: true
    #defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: always
      #schema-locations: classpath:schema.sql.bak
      #data-locations: classpath:sql/data-test.sql
      continue-on-error: false

# Test Logging
logging:
  level:
    root: INFO
    com.pragma.vc.tracker: DEBUG
    org.springframework.web: INFO
    org.springframework.test: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Server Configuration
server:
  port: ${TEST_SERVER_PORT:8081}  # Different port to avoid conflicts
  error:
    include-stacktrace: on_param