# Test Profile Configuration
# Uses PostgreSQL for integration testing

spring:
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/knowledge_tracker_test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none  # Use schema.sql.bak for tests
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: always
      #schema-locations: classpath:schema.sql.bak
      #data-locations: classpath:data.sql.old
      continue-on-error: false

# Test Logging
logging:
  level:
    root: INFO
    com.pragma.vc.tracker: DEBUG
    org.springframework.web: INFO
    org.springframework.test: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Server Configuration
server:
  port: 8081  # Different port to avoid conflicts
  error:
    include-stacktrace: on_param