-- ============================================
-- Knowledge Tracker Database Schema
-- PostgreSQL Compatible DDL
-- Generated from JPA Entities
-- ============================================
--
-- This schema supports a Modular Monolith Architecture with the following modules:
-- - Project Management (Client/Account & Project entities)
-- - People Management (Organization structure: Territory, KC-Team, Chapter, Pragmatic)
-- - Knowledge Catalog (Category, Knowledge, Level)
-- - Knowledge Application (Applied Knowledge - Core Domain)
-- - User Management (User authentication and authorization)
-- ============================================

-- Drop existing tables if needed (in correct dependency order)
DROP TABLE IF EXISTS "Applied_Knowledge" CASCADE;
DROP TABLE IF EXISTS "Pragmatic" CASCADE;
DROP TABLE IF EXISTS "Project" CASCADE;
DROP TABLE IF EXISTS "account" CASCADE;
DROP TABLE IF EXISTS "knowledge" CASCADE;
DROP TABLE IF EXISTS "Knowledge_Category" CASCADE;
DROP TABLE IF EXISTS "Knowledge_Level" CASCADE;
DROP TABLE IF EXISTS "Chapter" CASCADE;
DROP TABLE IF EXISTS "KC-Team" CASCADE;
DROP TABLE IF EXISTS "territory" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

-- ============================================
-- BASE TABLES (No Foreign Key Dependencies)
-- ============================================

-- Territory Table (Project Management Module)
CREATE TABLE "territory" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL UNIQUE,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY("id")
);

COMMENT ON TABLE "territory" IS 'Geographical territories/regions for organizational structure';
COMMENT ON COLUMN "territory"."name" IS 'Territory name (e.g., Colombia, Mexico, USA)';

-- KC-Team Table (People Management Module)
CREATE TABLE "KC-Team" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL UNIQUE,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY("id")
);

COMMENT ON TABLE "KC-Team" IS 'Knowledge Center Teams - organizational units within Pragma SA';

-- Knowledge_Category Table (Knowledge Catalog Module)
CREATE TABLE "Knowledge_Category" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(50) NOT NULL UNIQUE,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY("id")
);

COMMENT ON TABLE "Knowledge_Category" IS 'Categories of technical knowledge (Platform, Language, Framework, Tool, Technique)';

-- Knowledge_Level Table (Knowledge Catalog Module)
CREATE TABLE "Knowledge_Level" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "attributes" JSONB,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY("id")
);

COMMENT ON TABLE "Knowledge_Level" IS 'Proficiency levels for knowledge application (Beginner, Intermediate, Advanced, Expert)';

-- User Table (User Management Module)
CREATE TABLE "User" (
    "id" UUID NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "first_name" VARCHAR(100) NOT NULL,
    "last_name" VARCHAR(100) NOT NULL,
    "system_role" VARCHAR(50) NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY("id"),
    CONSTRAINT "chk_user_email_format"
        CHECK ("email" ~* '^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT "chk_user_system_role"
        CHECK ("system_role" IN ('FULL_ADMINISTRATOR', 'KNOWLEDGE_MANAGER', 'PROJECT_ACCOUNT_MANAGER', 'PEOPLE_MANAGER', 'USER'))
);

COMMENT ON TABLE "User" IS 'System users with authentication and authorization information';
COMMENT ON COLUMN "User"."id" IS 'Unique UUID identifier for the user';
COMMENT ON COLUMN "User"."email" IS 'User email address - used for login (unique, indexed)';
COMMENT ON COLUMN "User"."system_role" IS 'User role: FULL_ADMINISTRATOR, KNOWLEDGE_MANAGER, PROJECT_ACCOUNT_MANAGER, PEOPLE_MANAGER, USER';
COMMENT ON COLUMN "User"."active" IS 'Whether the user account is active';

-- ============================================
-- SECOND LEVEL TABLES (Single FK Dependencies)
-- ============================================

-- Account Table (Project Management Module)
CREATE TABLE "account" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "territory_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "status" VARCHAR(255),
    "attributes" JSONB,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY("id"),
    CONSTRAINT "fk_account_territory"
        FOREIGN KEY("territory_id")
        REFERENCES "territory"("id")
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

COMMENT ON TABLE "account" IS 'Client accounts/organizations that Pragma SA works with';

-- Chapter Table (People Management Module)
CREATE TABLE "Chapter" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kc_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "status" VARCHAR(50) NOT NULL DEFAULT 'Active',
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY("id"),
    CONSTRAINT "fk_chapter_kc_team"
        FOREIGN KEY("kc_id")
        REFERENCES "KC-Team"("id")
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

COMMENT ON TABLE "Chapter" IS 'Chapters within KC-Teams - sub-organizational units';

-- knowledge Table (Knowledge Catalog Module)
CREATE TABLE "knowledge" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "category_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" VARCHAR(500),
    "approved_status" VARCHAR(255),
    "attributes" JSONB,
    PRIMARY KEY("id"),
    CONSTRAINT "fk_knowledge_category"
        FOREIGN KEY("category_id")
        REFERENCES "Knowledge_Category"("id")
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

COMMENT ON TABLE "knowledge" IS 'Technical knowledge items that can be applied to projects';

-- ============================================
-- THIRD LEVEL TABLES (Multiple FK Dependencies)
-- ============================================

-- Project Table (Project Management Module)
CREATE TABLE "Project" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "account_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'Active',
    "start_date" DATE NOT NULL,
    "end_date" DATE,
    "type" VARCHAR(255) DEFAULT 'Abierto',
    "attributes" JSONB,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY("id"),
    CONSTRAINT "fk_project_account"
        FOREIGN KEY("account_id")
        REFERENCES "account"("id")
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

COMMENT ON TABLE "Project" IS 'Client projects where Pragmatics apply their knowledge';
COMMENT ON COLUMN "Project"."type" IS 'Project type: Abierto (open), Cerrado (closed), N/A';
COMMENT ON COLUMN "Project"."status" IS 'Project status: Active, Inactive, Completed';

-- Pragmatic Table (People Management Module)
CREATE TABLE "Pragmatic" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "chapter_id" BIGINT NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "first_name" VARCHAR(100),
    "last_name" VARCHAR(100),
    "status" VARCHAR(50) DEFAULT 'Active',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "attributes" JSONB,
    PRIMARY KEY("id"),
    CONSTRAINT "fk_pragmatic_chapter"
        FOREIGN KEY("chapter_id")
        REFERENCES "Chapter"("id")
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

COMMENT ON TABLE "Pragmatic" IS 'Pragma SA employees (consultants) who work on client projects';
COMMENT ON COLUMN "Pragmatic"."status" IS 'Employee status: Active, Inactive, OnLeave';

-- ============================================
-- CORE DOMAIN TABLE (Junction/Association Table)
-- ============================================

-- Applied_Knowledge Table (Knowledge Application Module - CORE DOMAIN)
CREATE TABLE "Applied_Knowledge" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "project_id" BIGINT NOT NULL,
    "pragmatic_id" BIGINT NOT NULL,
    "knowledge_id" BIGINT NOT NULL,
    "onboard_date" DATE NOT NULL,
    "offboard_date" DATE,
    "knowledge_level" BIGINT NOT NULL,
    "attributes" JSONB,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY("id"),
    CONSTRAINT "fk_applied_knowledge_project"
        FOREIGN KEY("project_id")
        REFERENCES "Project"("id")
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT "fk_applied_knowledge_pragmatic"
        FOREIGN KEY("pragmatic_id")
        REFERENCES "Pragmatic"("id")
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT "fk_applied_knowledge_knowledge"
        FOREIGN KEY("knowledge_id")
        REFERENCES "knowledge"("id")
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT "fk_applied_knowledge_level"
        FOREIGN KEY("knowledge_level")
        REFERENCES "Knowledge_Level"("id")
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT "chk_dates"
        CHECK ("offboard_date" IS NULL OR "offboard_date" >= "onboard_date")
);

COMMENT ON TABLE "Applied_Knowledge" IS 'CORE DOMAIN: Records which Pragmatic applied which Knowledge to which Project, at what proficiency level, and for what time period';
COMMENT ON COLUMN "Applied_Knowledge"."onboard_date" IS 'Date when the Pragmatic started applying this knowledge on the project';
COMMENT ON COLUMN "Applied_Knowledge"."offboard_date" IS 'Date when the Pragmatic stopped applying this knowledge on the project (NULL if still active)';

-- ============================================
-- PERFORMANCE INDEXES
-- ============================================

-- Applied_Knowledge indexes (most queried table)
CREATE INDEX "idx_applied_knowledge_composite"
    ON "Applied_Knowledge" ("project_id", "pragmatic_id", "knowledge_id");

CREATE INDEX "idx_applied_knowledge_project"
    ON "Applied_Knowledge" ("project_id");

CREATE INDEX "idx_applied_knowledge_pragmatic"
    ON "Applied_Knowledge" ("pragmatic_id");

CREATE INDEX "idx_applied_knowledge_knowledge"
    ON "Applied_Knowledge" ("knowledge_id");

CREATE INDEX "idx_applied_knowledge_level"
    ON "Applied_Knowledge" ("knowledge_level");

CREATE INDEX "idx_applied_knowledge_dates"
    ON "Applied_Knowledge" ("onboard_date", "offboard_date");

-- Foreign key indexes for join performance
CREATE INDEX "idx_project_account"
    ON "Project" ("account_id");

CREATE INDEX "idx_project_status"
    ON "Project" ("status");

CREATE INDEX "idx_pragmatic_chapter"
    ON "Pragmatic" ("chapter_id");

CREATE INDEX "idx_pragmatic_email"
    ON "Pragmatic" ("email");

CREATE INDEX "idx_pragmatic_status"
    ON "Pragmatic" ("status");

CREATE INDEX "idx_account_territory"
    ON "account" ("territory_id");

CREATE INDEX "idx_chapter_kc"
    ON "Chapter" ("kc_id");

CREATE INDEX "idx_knowledge_category"
    ON "knowledge" ("category_id");

-- User indexes
CREATE UNIQUE INDEX "idx_user_email"
    ON "User" ("email");

CREATE INDEX "idx_user_system_role"
    ON "User" ("system_role");

CREATE INDEX "idx_user_active"
    ON "User" ("active");

-- ============================================
-- DATABASE STATISTICS (for query optimization)
-- ============================================

-- Ensure PostgreSQL gathers statistics on all tables for optimal query planning
ANALYZE "territory";
ANALYZE "KC-Team";
ANALYZE "Knowledge_Category";
ANALYZE "Knowledge_Level";
ANALYZE "User";
ANALYZE "account";
ANALYZE "Chapter";
ANALYZE "knowledge";
ANALYZE "Project";
ANALYZE "Pragmatic";
ANALYZE "Applied_Knowledge";

-- ============================================
-- SEED DATA - System Roles Documentation
-- ============================================

-- System Roles available in the application:
-- 1. FULL_ADMINISTRATOR    - Complete system access, can perform all operations
-- 2. KNOWLEDGE_MANAGER     - Can create and manage knowledge items and applied knowledge
-- 3. PROJECT_ACCOUNT_MANAGER - Can create and manage projects and client accounts
-- 4. PEOPLE_MANAGER        - Can create and update Pragmatics (employees)
-- 5. USER                  - Default role, read-only access for queries

-- Example: Create a default administrator user
-- INSERT INTO "User" ("id", "email", "first_name", "last_name", "system_role", "active", "created_at")
-- VALUES (
--     gen_random_uuid(),
--     'admin@pragma.com.co',
--     'System',
--     'Administrator',
--     'FULL_ADMINISTRATOR',
--     true,
--     CURRENT_TIMESTAMP
-- );

-- ============================================
-- END OF SCHEMA
-- ============================================
